version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"  
    environment:
      - JWT_SECRET=ed32f7e00f987d83e8bae457abd38782f886d44e61da11ec291d4aba34fe1d6b1f1a472940286947b5b586ca2bba9891c1e2b8b7236893ac5a61bbd5b19bae20
      - MONGO_URI=mongodb+srv://angelramos:1121707024An@kach.hini0.mongodb.net/?retryWrites=true&w=majority&appName=kach` 
      - OPENAI_API_KEY=sk-svcacct-A-srkIoPvIdWDjYFZ3I8LwOZV-bwN4sp8lHqrVZwwgzT3BlbkFJUkEuN0I1EsmDG8JaIfdQ-c2IUPOjnMkzvz27YDbrAAA 
    depends_on:
      - mongo  

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:  
